apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: jenkins
  name: jenkins
  namespace: devops
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32100
  selector:
    run: jenkins
  type: NodePort
status:
  loadBalancer: {}
